### ISSUE TITLE
"invalid_api_key"

### ISSUE THREAD

**Issue by ghost** [Pasquale007/HelperAI#1]
_It says: "invalid_api_key." I am using Lua, I was looking for any wrong code and it told me it's invalid_

**Comment by Pasquale007** [comment]
Hi, are you sure you have registered a valid API key? I can no longer afford to use my own key. Maybe you can work through the README and check if you have followed these steps. If the error still occurs, I will check.

**Comment by ghost** [comment]
Okay, I will let you know for anything.
